---
language: python

python:
  - "3.6"

install:
  - pip install ansible ansible-lint molecule[docker]

script:
  - ansible-galaxy install ultral.ansible_docker_centos
  - molecule --debug lint
  - molecule --debug syntax

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
