---
- name: ansible dev software are installed
  yum:
    name: "{{ ansible_dev__software }}"
    state: present
  retries: 10
  delay: 5


- name: setuptools latest verstion is installed
  pip:
    name: setuptools>=20.1.1
    state: present
    executable: pip3
  retries: 10
  delay: 5

- name: pip modules are installed
  pip:
    name: "{{ ansible_dev__pip_modules }}"
    executable: pip3
    state: present
  retries: 10
  delay: 5

- name: PATH caontains /usr/local/bin
  copy:
    dest: /etc/profile.d/local.sh
    content: export PATH=${PATH}:/usr/local/bin
    mode: 0755
