---
- name: ansible dev software are installed
  yum:
    name: "{{ ansible_dev__software }}"
    state: present

- name: setuptools latest verstion is installed
  pip:
    name:
      - setuptools
      - wheel
    executable: pip3
    state: latest

- name: pip modules are installed
  pip:
    name: "{{ ansible_dev__pip_modules }}"
    executable: pip3
    state: present

- name: PATH caontains /usr/local/bin
  copy:
    dest: /etc/profile.d/local.sh
    content: export PATH=${PATH}:/usr/local/bin
    mode: 0755
